local gruvbox = {
   dark0_hard = "#1d2021",
   dark0 = "#282828",
   dark0_soft = "#32302f",
   dark1 = "#3c3836",
   dark2 = "#504945",
   dark3 = "#665c54",
   dark4 = "#7c6f64",
   light0_hard = "#f9f5d7",
   light0 = "#fbf1c7",
   light0_soft = "#f2e5bc",
   light1 = "#ebdbb2",
   light2 = "#d5c4a1",
   light3 = "#bdae93",
   light4 = "#a89984",
   bright_red = "#fb4934",
   bright_green = "#b8bb26",
   bright_yellow = "#fabd2f",
   bright_blue = "#83a598",
   bright_purple = "#d3869b",
   bright_aqua = "#8ec07c",
   bright_orange = "#fe8019",
   bright_gray = "#a89984",
   neutral_red = "#cc241d",
   neutral_green = "#98971a",
   neutral_yellow = "#d79921",
   neutral_blue = "#458588",
   neutral_purple = "#b16286",
   neutral_aqua = "#689d6a",
   neutral_orange = "#d65d0e",
   neutral_gray = "#928374",
   faded_red = "#9d0006",
   faded_green = "#79740e",
   faded_yellow = "#b57614",
   faded_blue = "#076678",
   faded_purple = "#8f3f71",
   faded_aqua = "#427b58",
   faded_orange = "#af3a03",
   faded_gray = "#7c6f64",
}

local bg = vim.o.background
if bg == nil then
   bg = "dark"
   vim.o.background = bg
end

local colors = {}

if bg == "dark" then
   colors = {
      bg0 = gruvbox.dark0,
      bg0_h = gruvbox.dark0_hard,
      bg0_s = gruvbox.dark0_soft,
      bg1 = gruvbox.dark1,
      bg2 = gruvbox.dark2,
      bg3 = gruvbox.dark3,
      bg4 = gruvbox.dark4,
      fg0 = gruvbox.light0,
      fg0_h = gruvbox.light0_hard,
      fg0_s = gruvbox.light0_soft,
      fg1 = gruvbox.light1,
      fg2 = gruvbox.light2,
      fg3 = gruvbox.light3,
      fg4 = gruvbox.light4,
      red = gruvbox.bright_red,
      green = gruvbox.bright_green,
      yellow = gruvbox.bright_yellow,
      blue = gruvbox.bright_blue,
      purple = gruvbox.bright_purple,
      aqua = gruvbox.bright_aqua,
      orange = gruvbox.bright_orange,
      gray = gruvbox.bright_gray,
      red_a = gruvbox.neutral_red,
      green_a = gruvbox.neutral_green,
      yellow_a = gruvbox.neutral_yellow,
      blue_a = gruvbox.neutral_blue,
      purple_a = gruvbox.neutral_purple,
      aqua_a = gruvbox.neutral_aqua,
      orange_a = gruvbox.neutral_orange,
      gray_a = gruvbox.neutral_gray,
   }
else
   colors = {
      bg0 = gruvbox.light0,
      bg0_h = gruvbox.light0_hard,
      bg0_s = gruvbox.light0_soft,
      bg1 = gruvbox.light1,
      bg2 = gruvbox.light2,
      bg3 = gruvbox.light3,
      bg4 = gruvbox.light4,
      fg0 = gruvbox.dark0,
      fg0_h = gruvbox.dark0_hard,
      fg0_s = gruvbox.dark0_soft,
      fg1 = gruvbox.dark1,
      fg2 = gruvbox.dark2,
      fg3 = gruvbox.dark3,
      fg4 = gruvbox.dark4,
      red = gruvbox.faded_red,
      green = gruvbox.faded_green,
      yellow = gruvbox.faded_yellow,
      blue = gruvbox.faded_blue,
      purple = gruvbox.faded_purple,
      aqua = gruvbox.faded_aqua,
      orange = gruvbox.faded_orange,
      gray = gruvbox.faded_gray,
      red_a = gruvbox.neutral_red,
      green_a = gruvbox.neutral_green,
      yellow_a = gruvbox.neutral_yellow,
      blue_a = gruvbox.neutral_blue,
      purple_a = gruvbox.neutral_purple,
      aqua_a = gruvbox.neutral_aqua,
      orange_a = gruvbox.neutral_orange,
      gray_a = gruvbox.neutral_gray,
   }
end

return colors
